---
- name: Configurar cliente NFS
  hosts: localhost
  connection: local
  tasks:
    - name: Instalar NFS (importar tasks)
      ansible.builtin.import_tasks:
        file: 02_nfs/tasks/instalar_nfs.yml

    - name: Configurar NFS (importar tasks)
      ansible.builtin.import_tasks:
        file: 02_nfs/tasks/configurar_nfs.yml
