---
- name: Instalar pacotes apt essenciais
  hosts: localhost
  connection: local
  tasks:
    - name: Instalar apps extras (importar tasks)
      ansible.builtin.import_tasks:
        file: 04_aplicativos/tasks/apps_extras.yml
      when: (extras is defined) and (extras | bool)

    - name: Atualizar lista de pacotes (apt-get update)
      ansible.builtin.apt:
        update_cache: true

    - name: Instalar pacotes APT
      ansible.builtin.apt:
        name:
          - build-essential
          - cmake
          - curl
          - default-jdk
          - default-jdk-doc
          - fzf
          - gedit
          - gnumeric
          - htop
          - neovim
          - nscd
          - openssh-client
          - openssh-server
          - pkg-config
          - parallel
          - pipx
          - ssh
          - tmux
          - xterm
        state: present

    - name: Instalar Google Chrome
      ansible.builtin.apt:
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

    - name: Instalar Visual Studio Code
      ansible.builtin.apt:
        deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
