---
- import_playbook: 01_rede.yml
- import_playbook: 02_cliente_nfs.yml
- import_playbook: 03_cliente_nis.yml
- import_playbook: 04_aplicativos.yml
- import_playbook: 05_lightdm.yml
- import_playbook: 06_servidor_ssh.yml
